// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykdunxvspsesmxokqdyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZHVueHZzcHNlc214b2txZHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTkzODUsImV4cCI6MjA1ODM3NTM4NX0.j9nJn0DqWoPSpaab80ET_kTTUHyAN1TBPW55Gts_NEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);